
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Ball : Luban.BeanBase
{
    public Ball(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BallKind = (BallKind)_buf.ReadInt();
        PrefabLocation = _buf.ReadString();
        Mass = _buf.ReadFloat();
        RadiusMin = _buf.ReadFloat();
        RadiusMax = _buf.ReadFloat();
        if(_buf.ReadBool()){ ShotParams = global::GameConfig.ShotParams.DeserializeShotParams(_buf); } else { ShotParams = null; }
        if(_buf.ReadBool()){ SizeChangeParams = global::GameConfig.SizeChangeParams.DeserializeSizeChangeParams(_buf); } else { SizeChangeParams = null; }
    }

    public static Ball DeserializeBall(ByteBuf _buf)
    {
        return new Ball(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// ballKind
    /// </summary>
    public readonly BallKind BallKind;
    /// <summary>
    /// prefabLocation
    /// </summary>
    public readonly string PrefabLocation;
    /// <summary>
    /// mass
    /// </summary>
    public readonly float Mass;
    /// <summary>
    /// radiusMin
    /// </summary>
    public readonly float RadiusMin;
    /// <summary>
    /// radiusMax
    /// </summary>
    public readonly float RadiusMax;
    /// <summary>
    /// shotParams
    /// </summary>
    public readonly ShotParams ShotParams;
    /// <summary>
    /// sizeChangeParams
    /// </summary>
    public readonly SizeChangeParams SizeChangeParams;
   
    public const int __ID__ = 2062879;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ShotParams?.ResolveRef(tables);
        SizeChangeParams?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "ballKind:" + BallKind + ","
        + "prefabLocation:" + PrefabLocation + ","
        + "mass:" + Mass + ","
        + "radiusMin:" + RadiusMin + ","
        + "radiusMax:" + RadiusMax + ","
        + "shotParams:" + ShotParams + ","
        + "sizeChangeParams:" + SizeChangeParams + ","
        + "}";
    }
}
}

