
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Board : Luban.BeanBase
{
    public Board(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        PrefabLocation = _buf.ReadString();
        Min = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        Max = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        {int n0 = _buf.ReadSize(); PocketLayouts = new System.Collections.Generic.List<PocketLayout>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { PocketLayout _e0;  _e0 = global::GameConfig.PocketLayout.DeserializePocketLayout(_buf); PocketLayouts.Add(_e0);}}
        {int n0 = _buf.ReadSize(); PocketStyles = new System.Collections.Generic.List<PocketStyle>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { PocketStyle _e0;  _e0 = global::GameConfig.PocketStyle.DeserializePocketStyle(_buf); PocketStyles.Add(_e0);}}
        GeometryStyle = global::GameConfig.GeometryStyle.DeserializeGeometryStyle(_buf);
        PredictionStyle = global::GameConfig.PredictionStyle.DeserializePredictionStyle(_buf);
    }

    public static Board DeserializeBoard(ByteBuf _buf)
    {
        return new Board(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// prefabLocation
    /// </summary>
    public readonly string PrefabLocation;
    /// <summary>
    /// min
    /// </summary>
    public readonly UnityEngine.Vector2 Min;
    /// <summary>
    /// max
    /// </summary>
    public readonly UnityEngine.Vector2 Max;
    /// <summary>
    /// pocketLayouts
    /// </summary>
    public readonly System.Collections.Generic.List<PocketLayout> PocketLayouts;
    /// <summary>
    /// pocketStyles
    /// </summary>
    public readonly System.Collections.Generic.List<PocketStyle> PocketStyles;
    /// <summary>
    /// geometryStyle
    /// </summary>
    public readonly GeometryStyle GeometryStyle;
    /// <summary>
    /// predictionStyle
    /// </summary>
    public readonly PredictionStyle PredictionStyle;
   
    public const int __ID__ = 64356038;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in PocketLayouts) { _e?.ResolveRef(tables); }
        foreach (var _e in PocketStyles) { _e?.ResolveRef(tables); }
        GeometryStyle?.ResolveRef(tables);
        PredictionStyle?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "prefabLocation:" + PrefabLocation + ","
        + "min:" + Min + ","
        + "max:" + Max + ","
        + "pocketLayouts:" + Luban.StringUtil.CollectionToString(PocketLayouts) + ","
        + "pocketStyles:" + Luban.StringUtil.CollectionToString(PocketStyles) + ","
        + "geometryStyle:" + GeometryStyle + ","
        + "predictionStyle:" + PredictionStyle + ","
        + "}";
    }
}
}

