
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class FlipEffect : PropEffect
{
    public FlipEffect(ByteBuf _buf)  : base(_buf) 
    {
    }

    public static FlipEffect DeserializeFlipEffect(ByteBuf _buf)
    {
        return new FlipEffect(_buf);
    }

   
    public const int __ID__ = -1802191746;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

