
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class GeometryStyle : Luban.BeanBase
{
    public GeometryStyle(ByteBuf _buf) 
    {
        FigureColor = ExternalTypeUtil.NewVector4(global::GameConfig.vector4.Deserializevector4(_buf));
        CircleColor = ExternalTypeUtil.NewVector4(global::GameConfig.vector4.Deserializevector4(_buf));
        LineWidth = _buf.ReadFloat();
        PreviewColor = ExternalTypeUtil.NewVector4(global::GameConfig.vector4.Deserializevector4(_buf));
        PreviewLineWidth = _buf.ReadFloat();
        PreviewFailureThreshold = _buf.ReadInt();
        PreviewFailureInterval = _buf.ReadInt();
        PreviewDuration = _buf.ReadFloat();
    }

    public static GeometryStyle DeserializeGeometryStyle(ByteBuf _buf)
    {
        return new GeometryStyle(_buf);
    }

    public readonly UnityEngine.Vector4 FigureColor;
    public readonly UnityEngine.Vector4 CircleColor;
    public readonly float LineWidth;
    public readonly UnityEngine.Vector4 PreviewColor;
    public readonly float PreviewLineWidth;
    public readonly int PreviewFailureThreshold;
    public readonly int PreviewFailureInterval;
    public readonly float PreviewDuration;
   
    public const int __ID__ = -1263743937;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "figureColor:" + FigureColor + ","
        + "circleColor:" + CircleColor + ","
        + "lineWidth:" + LineWidth + ","
        + "previewColor:" + PreviewColor + ","
        + "previewLineWidth:" + PreviewLineWidth + ","
        + "previewFailureThreshold:" + PreviewFailureThreshold + ","
        + "previewFailureInterval:" + PreviewFailureInterval + ","
        + "previewDuration:" + PreviewDuration + ","
        + "}";
    }
}
}

