
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class LevelBall : Luban.BeanBase
{
    public LevelBall(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelId = _buf.ReadInt();
        LevelId_Ref = null;
        BallConfigId = _buf.ReadInt();
        BallConfigId_Ref = null;
        SpawnPosition = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        SpawnRadius = _buf.ReadFloat();
    }

    public static LevelBall DeserializeLevelBall(ByteBuf _buf)
    {
        return new LevelBall(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// levelId
    /// </summary>
    public readonly int LevelId;
    public Level LevelId_Ref;
    /// <summary>
    /// ballConfigId
    /// </summary>
    public readonly int BallConfigId;
    public Ball BallConfigId_Ref;
    /// <summary>
    /// spawnPosition
    /// </summary>
    public readonly UnityEngine.Vector2 SpawnPosition;
    /// <summary>
    /// spawnRadius
    /// </summary>
    public readonly float SpawnRadius;
   
    public const int __ID__ = 347198339;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        LevelId_Ref = tables.TbLevel.GetOrDefault(LevelId);
        BallConfigId_Ref = tables.TbBall.GetOrDefault(BallConfigId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "ballConfigId:" + BallConfigId + ","
        + "spawnPosition:" + SpawnPosition + ","
        + "spawnRadius:" + SpawnRadius + ","
        + "}";
    }
}
}

