
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class LevelProp : Luban.BeanBase
{
    public LevelProp(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelId = _buf.ReadInt();
        LevelId_Ref = null;
        PropConfigId = _buf.ReadInt();
        PropConfigId_Ref = null;
        Position = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        TriggerMode = (TriggerMode)_buf.ReadInt();
    }

    public static LevelProp DeserializeLevelProp(ByteBuf _buf)
    {
        return new LevelProp(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// levelId
    /// </summary>
    public readonly int LevelId;
    public Level LevelId_Ref;
    /// <summary>
    /// propConfigId
    /// </summary>
    public readonly int PropConfigId;
    public Prop PropConfigId_Ref;
    /// <summary>
    /// position
    /// </summary>
    public readonly UnityEngine.Vector2 Position;
    /// <summary>
    /// triggerMode
    /// </summary>
    public readonly TriggerMode TriggerMode;
   
    public const int __ID__ = 347631847;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        LevelId_Ref = tables.TbLevel.GetOrDefault(LevelId);
        PropConfigId_Ref = tables.TbProp.GetOrDefault(PropConfigId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "propConfigId:" + PropConfigId + ","
        + "position:" + Position + ","
        + "triggerMode:" + TriggerMode + ","
        + "}";
    }
}
}

