
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class LevelGeometry : Luban.BeanBase
{
    public LevelGeometry(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelId = _buf.ReadInt();
        LevelId_Ref = null;
        Shape = global::GameConfig.Shape.DeserializeShape(_buf);
        Position = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        Rotation = _buf.ReadFloat();
        UniformScale = _buf.ReadFloat();
        ConditionKind = (ConditionKind)_buf.ReadInt();
        Tolerance = _buf.ReadFloat();
        AllowedBallKind = (BallKind)_buf.ReadInt();
        EffectBinding = global::GameConfig.EffectBinding.DeserializeEffectBinding(_buf);
    }

    public static LevelGeometry DeserializeLevelGeometry(ByteBuf _buf)
    {
        return new LevelGeometry(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// levelId
    /// </summary>
    public readonly int LevelId;
    public Level LevelId_Ref;
    /// <summary>
    /// shape
    /// </summary>
    public readonly Shape Shape;
    /// <summary>
    /// position
    /// </summary>
    public readonly UnityEngine.Vector2 Position;
    /// <summary>
    /// rotation
    /// </summary>
    public readonly float Rotation;
    /// <summary>
    /// uniformScale
    /// </summary>
    public readonly float UniformScale;
    /// <summary>
    /// conditionKind
    /// </summary>
    public readonly ConditionKind ConditionKind;
    /// <summary>
    /// tolerance
    /// </summary>
    public readonly float Tolerance;
    /// <summary>
    /// allowedBallKind
    /// </summary>
    public readonly BallKind AllowedBallKind;
    /// <summary>
    /// effectBinding
    /// </summary>
    public readonly EffectBinding EffectBinding;
   
    public const int __ID__ = -652119050;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        LevelId_Ref = tables.TbLevel.GetOrDefault(LevelId);
        Shape?.ResolveRef(tables);
        EffectBinding?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "shape:" + Shape + ","
        + "position:" + Position + ","
        + "rotation:" + Rotation + ","
        + "uniformScale:" + UniformScale + ","
        + "conditionKind:" + ConditionKind + ","
        + "tolerance:" + Tolerance + ","
        + "allowedBallKind:" + AllowedBallKind + ","
        + "effectBinding:" + EffectBinding + ","
        + "}";
    }
}
}

