
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class LevelTerrain : Luban.BeanBase
{
    public LevelTerrain(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelId = _buf.ReadInt();
        LevelId_Ref = null;
        TerrainConfigId = _buf.ReadInt();
        TerrainConfigId_Ref = null;
        Position = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        Size = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        Direction = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        TriggerRadius = _buf.ReadFloat();
        Duration = _buf.ReadFloat();
        ExitId = _buf.ReadInt();
    }

    public static LevelTerrain DeserializeLevelTerrain(ByteBuf _buf)
    {
        return new LevelTerrain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// levelId
    /// </summary>
    public readonly int LevelId;
    public Level LevelId_Ref;
    /// <summary>
    /// terrainConfigId
    /// </summary>
    public readonly int TerrainConfigId;
    public Terrain TerrainConfigId_Ref;
    /// <summary>
    /// position
    /// </summary>
    public readonly UnityEngine.Vector2 Position;
    /// <summary>
    /// size
    /// </summary>
    public readonly UnityEngine.Vector2 Size;
    /// <summary>
    /// direction
    /// </summary>
    public readonly UnityEngine.Vector2 Direction;
    /// <summary>
    /// triggerRadius
    /// </summary>
    public readonly float TriggerRadius;
    /// <summary>
    /// duration
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// exitId
    /// </summary>
    public readonly int ExitId;
   
    public const int __ID__ = 19998513;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        LevelId_Ref = tables.TbLevel.GetOrDefault(LevelId);
        TerrainConfigId_Ref = tables.TbTerrain.GetOrDefault(TerrainConfigId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "terrainConfigId:" + TerrainConfigId + ","
        + "position:" + Position + ","
        + "size:" + Size + ","
        + "direction:" + Direction + ","
        + "triggerRadius:" + TriggerRadius + ","
        + "duration:" + Duration + ","
        + "exitId:" + ExitId + ","
        + "}";
    }
}
}

