
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Level : Luban.BeanBase
{
    public Level(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Order = _buf.ReadInt();
        BoardConfigId = _buf.ReadInt();
        BoardConfigId_Ref = null;
        PhysicsConfigId = _buf.ReadInt();
        PhysicsConfigId_Ref = null;
        MaxShots = _buf.ReadInt();
        ShowGeometryHintsByDefault = _buf.ReadBool();
        Difficulty = _buf.ReadString();
        Objective = _buf.ReadString();
        PredictionPropCount = _buf.ReadInt();
    }

    public static Level DeserializeLevel(ByteBuf _buf)
    {
        return new Level(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// order
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// boardConfigId
    /// </summary>
    public readonly int BoardConfigId;
    public Board BoardConfigId_Ref;
    /// <summary>
    /// physicsConfigId
    /// </summary>
    public readonly int PhysicsConfigId;
    public Physics PhysicsConfigId_Ref;
    /// <summary>
    /// maxShots
    /// </summary>
    public readonly int MaxShots;
    /// <summary>
    /// showGeometryHintsByDefault
    /// </summary>
    public readonly bool ShowGeometryHintsByDefault;
    /// <summary>
    /// difficulty
    /// </summary>
    public readonly string Difficulty;
    /// <summary>
    /// objective
    /// </summary>
    public readonly string Objective;
    /// <summary>
    /// 折射预测道具次数
    /// </summary>
    public readonly int PredictionPropCount;
   
    public const int __ID__ = 73313124;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        BoardConfigId_Ref = tables.TbBoard.GetOrDefault(BoardConfigId);
        PhysicsConfigId_Ref = tables.TbPhysics.GetOrDefault(PhysicsConfigId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "order:" + Order + ","
        + "boardConfigId:" + BoardConfigId + ","
        + "physicsConfigId:" + PhysicsConfigId + ","
        + "maxShots:" + MaxShots + ","
        + "showGeometryHintsByDefault:" + ShowGeometryHintsByDefault + ","
        + "difficulty:" + Difficulty + ","
        + "objective:" + Objective + ","
        + "predictionPropCount:" + PredictionPropCount + ","
        + "}";
    }
}
}

