
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class LevelPocket : Luban.BeanBase
{
    public LevelPocket(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelId = _buf.ReadInt();
        LevelId_Ref = null;
        Slot = (PocketSlot)_buf.ReadInt();
        InitialState = (PocketState)_buf.ReadInt();
    }

    public static LevelPocket DeserializeLevelPocket(ByteBuf _buf)
    {
        return new LevelPocket(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// levelId
    /// </summary>
    public readonly int LevelId;
    public Level LevelId_Ref;
    /// <summary>
    /// slot
    /// </summary>
    public readonly PocketSlot Slot;
    /// <summary>
    /// initialState
    /// </summary>
    public readonly PocketState InitialState;
   
    public const int __ID__ = -936373734;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        LevelId_Ref = tables.TbLevel.GetOrDefault(LevelId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "slot:" + Slot + ","
        + "initialState:" + InitialState + ","
        + "}";
    }
}
}

