
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Physics : Luban.BeanBase
{
    public Physics(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SimulationStep = _buf.ReadFloat();
        BallRestitution = _buf.ReadFloat();
        RailRestitution = _buf.ReadFloat();
        GeometryRestitution = _buf.ReadFloat();
        ContactTolerance = _buf.ReadFloat();
        StopSpeed = _buf.ReadFloat();
        MaxEventIterations = _buf.ReadInt();
        PredictionBudget = _buf.ReadInt();
        DecelerationModel = (DecelerationModel)_buf.ReadInt();
    }

    public static Physics DeserializePhysics(ByteBuf _buf)
    {
        return new Physics(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// simulationStep
    /// </summary>
    public readonly float SimulationStep;
    /// <summary>
    /// ballRestitution
    /// </summary>
    public readonly float BallRestitution;
    /// <summary>
    /// railRestitution
    /// </summary>
    public readonly float RailRestitution;
    /// <summary>
    /// geometryRestitution
    /// </summary>
    public readonly float GeometryRestitution;
    /// <summary>
    /// contactTolerance
    /// </summary>
    public readonly float ContactTolerance;
    /// <summary>
    /// stopSpeed
    /// </summary>
    public readonly float StopSpeed;
    /// <summary>
    /// maxEventIterations
    /// </summary>
    public readonly int MaxEventIterations;
    /// <summary>
    /// predictionBudget
    /// </summary>
    public readonly int PredictionBudget;
    /// <summary>
    /// decelerationModel
    /// </summary>
    public readonly DecelerationModel DecelerationModel;
   
    public const int __ID__ = 1078558247;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "simulationStep:" + SimulationStep + ","
        + "ballRestitution:" + BallRestitution + ","
        + "railRestitution:" + RailRestitution + ","
        + "geometryRestitution:" + GeometryRestitution + ","
        + "contactTolerance:" + ContactTolerance + ","
        + "stopSpeed:" + StopSpeed + ","
        + "maxEventIterations:" + MaxEventIterations + ","
        + "predictionBudget:" + PredictionBudget + ","
        + "decelerationModel:" + DecelerationModel + ","
        + "}";
    }
}
}

