
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class PocketStyle : Luban.BeanBase
{
    public PocketStyle(ByteBuf _buf) 
    {
        State = (PocketState)_buf.ReadInt();
        Color = ExternalTypeUtil.NewVector4(global::GameConfig.vector4.Deserializevector4(_buf));
    }

    public static PocketStyle DeserializePocketStyle(ByteBuf _buf)
    {
        return new PocketStyle(_buf);
    }

    public readonly PocketState State;
    public readonly UnityEngine.Vector4 Color;
   
    public const int __ID__ = -562803301;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "state:" + State + ","
        + "color:" + Color + ","
        + "}";
    }
}
}

