
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum PocketSlot
    {
        TopLeft = 0,
        TopMiddle = 1,
        TopRight = 2,
        BottomLeft = 3,
        BottomMiddle = 4,
        BottomRight = 5,
    }

} 

