
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class PocketLayout : Luban.BeanBase
{
    public PocketLayout(ByteBuf _buf) 
    {
        Slot = (PocketSlot)_buf.ReadInt();
        Offset = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        MouthWidth = _buf.ReadFloat();
        CaptureRadius = _buf.ReadFloat();
    }

    public static PocketLayout DeserializePocketLayout(ByteBuf _buf)
    {
        return new PocketLayout(_buf);
    }

    public readonly PocketSlot Slot;
    public readonly UnityEngine.Vector2 Offset;
    public readonly float MouthWidth;
    public readonly float CaptureRadius;
   
    public const int __ID__ = -484980608;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "slot:" + Slot + ","
        + "offset:" + Offset + ","
        + "mouthWidth:" + MouthWidth + ","
        + "captureRadius:" + CaptureRadius + ","
        + "}";
    }
}
}

