
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class PredictionStyle : Luban.BeanBase
{
    public PredictionStyle(ByteBuf _buf) 
    {
        Color = ExternalTypeUtil.NewVector4(global::GameConfig.vector4.Deserializevector4(_buf));
        LineWidth = _buf.ReadFloat();
        DashLength = _buf.ReadFloat();
        GapLength = _buf.ReadFloat();
        DotDiameter = _buf.ReadFloat();
    }

    public static PredictionStyle DeserializePredictionStyle(ByteBuf _buf)
    {
        return new PredictionStyle(_buf);
    }

    public readonly UnityEngine.Vector4 Color;
    public readonly float LineWidth;
    public readonly float DashLength;
    public readonly float GapLength;
    public readonly float DotDiameter;
   
    public const int __ID__ = -917643710;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "color:" + Color + ","
        + "lineWidth:" + LineWidth + ","
        + "dashLength:" + DashLength + ","
        + "gapLength:" + GapLength + ","
        + "dotDiameter:" + DotDiameter + ","
        + "}";
    }
}
}

