
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class PreviewEffect : PropEffect
{
    public PreviewEffect(ByteBuf _buf)  : base(_buf) 
    {
    }

    public static PreviewEffect DeserializePreviewEffect(ByteBuf _buf)
    {
        return new PreviewEffect(_buf);
    }

   
    public const int __ID__ = 748405593;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "durationShots:" + DurationShots + ","
        + "rateMultiplier:" + RateMultiplier + ","
        + "targetPocketId:" + TargetPocketId + ","
        + "}";
    }
}
}

