
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum PropKind
    {
        Flip = 0,
        Reverse = 1,
        Freeze = 2,
        Restore = 3,
        FastChange = 4,
        Reveal = 5,
        Preview = 6,
        AddShot = 7,
        Key = 8,
    }

} 

