
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public abstract partial class PropEffect : Luban.BeanBase
{
    public PropEffect(ByteBuf _buf) 
    {
        DurationShots = _buf.ReadInt();
        RateMultiplier = _buf.ReadFloat();
        TargetPocketId = _buf.ReadInt();
    }

    public static PropEffect DeserializePropEffect(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case FlipEffect.__ID__: return new FlipEffect(_buf);
            case ReverseEffect.__ID__: return new ReverseEffect(_buf);
            case FreezeEffect.__ID__: return new FreezeEffect(_buf);
            case RestoreEffect.__ID__: return new RestoreEffect(_buf);
            case FastChangeEffect.__ID__: return new FastChangeEffect(_buf);
            case RevealEffect.__ID__: return new RevealEffect(_buf);
            case PreviewEffect.__ID__: return new PreviewEffect(_buf);
            case AddShotEffect.__ID__: return new AddShotEffect(_buf);
            case KeyEffect.__ID__: return new KeyEffect(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int DurationShots;
    public readonly float RateMultiplier;
    public readonly int TargetPocketId;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "durationShots:" + DurationShots + ","
        + "rateMultiplier:" + RateMultiplier + ","
        + "targetPocketId:" + TargetPocketId + ","
        + "}";
    }
}
}

