
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Prop : Luban.BeanBase
{
    public Prop(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        PropKind = (PropKind)_buf.ReadInt();
        PrefabLocation = _buf.ReadString();
        VisualDiameter = _buf.ReadFloat();
        TriggerRadius = _buf.ReadFloat();
        EffectParams = global::GameConfig.PropEffect.DeserializePropEffect(_buf);
        UseScope = (UseScope)_buf.ReadInt();
        UseLimit = _buf.ReadInt();
    }

    public static Prop DeserializeProp(ByteBuf _buf)
    {
        return new Prop(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// propKind
    /// </summary>
    public readonly PropKind PropKind;
    /// <summary>
    /// prefabLocation
    /// </summary>
    public readonly string PrefabLocation;
    /// <summary>
    /// visualDiameter
    /// </summary>
    public readonly float VisualDiameter;
    /// <summary>
    /// triggerRadius
    /// </summary>
    public readonly float TriggerRadius;
    /// <summary>
    /// effectParams
    /// </summary>
    public readonly PropEffect EffectParams;
    /// <summary>
    /// useScope
    /// </summary>
    public readonly UseScope UseScope;
    /// <summary>
    /// useLimit
    /// </summary>
    public readonly int UseLimit;
   
    public const int __ID__ = 2496387;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        EffectParams?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "propKind:" + PropKind + ","
        + "prefabLocation:" + PrefabLocation + ","
        + "visualDiameter:" + VisualDiameter + ","
        + "triggerRadius:" + TriggerRadius + ","
        + "effectParams:" + EffectParams + ","
        + "useScope:" + UseScope + ","
        + "useLimit:" + UseLimit + ","
        + "}";
    }
}
}

