
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class ShotParams : Luban.BeanBase
{
    public ShotParams(ByteBuf _buf) 
    {
        ChargeDuration = _buf.ReadFloat();
        SpeedMin = _buf.ReadFloat();
        SpeedMax = _buf.ReadFloat();
        RadiusMin = _buf.ReadFloat();
        RadiusMax = _buf.ReadFloat();
        DistanceMin = _buf.ReadFloat();
        DistanceMax = _buf.ReadFloat();
    }

    public static ShotParams DeserializeShotParams(ByteBuf _buf)
    {
        return new ShotParams(_buf);
    }

    public readonly float ChargeDuration;
    public readonly float SpeedMin;
    public readonly float SpeedMax;
    public readonly float RadiusMin;
    public readonly float RadiusMax;
    public readonly float DistanceMin;
    public readonly float DistanceMax;
   
    public const int __ID__ = 10615104;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "chargeDuration:" + ChargeDuration + ","
        + "speedMin:" + SpeedMin + ","
        + "speedMax:" + SpeedMax + ","
        + "radiusMin:" + RadiusMin + ","
        + "radiusMax:" + RadiusMax + ","
        + "distanceMin:" + DistanceMin + ","
        + "distanceMax:" + DistanceMax + ","
        + "}";
    }
}
}

