
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class SizeChangeParams : Luban.BeanBase
{
    public SizeChangeParams(ByteBuf _buf) 
    {
        GrowRateMin = _buf.ReadFloat();
        GrowRateMax = _buf.ReadFloat();
        ShrinkRate = _buf.ReadFloat();
    }

    public static SizeChangeParams DeserializeSizeChangeParams(ByteBuf _buf)
    {
        return new SizeChangeParams(_buf);
    }

    public readonly float GrowRateMin;
    public readonly float GrowRateMax;
    public readonly float ShrinkRate;
   
    public const int __ID__ = -1194462185;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "growRateMin:" + GrowRateMin + ","
        + "growRateMax:" + GrowRateMax + ","
        + "shrinkRate:" + ShrinkRate + ","
        + "}";
    }
}
}

