
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    /// <summary>
    /// Level
    /// </summary>
    public TbLevel TbLevel {get; }
    /// <summary>
    /// Board
    /// </summary>
    public TbBoard TbBoard {get; }
    /// <summary>
    /// Ball
    /// </summary>
    public TbBall TbBall {get; }
    /// <summary>
    /// Prop
    /// </summary>
    public TbProp TbProp {get; }
    /// <summary>
    /// Physics
    /// </summary>
    public TbPhysics TbPhysics {get; }
    /// <summary>
    /// LevelBall
    /// </summary>
    public TbLevelBall TbLevelBall {get; }
    /// <summary>
    /// LevelPocket
    /// </summary>
    public TbLevelPocket TbLevelPocket {get; }
    /// <summary>
    /// LevelProp
    /// </summary>
    public TbLevelProp TbLevelProp {get; }
    /// <summary>
    /// LevelGeometry
    /// </summary>
    public TbLevelGeometry TbLevelGeometry {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbLevel = new TbLevel(loader("tblevel"));
        TbBoard = new TbBoard(loader("tbboard"));
        TbBall = new TbBall(loader("tbball"));
        TbProp = new TbProp(loader("tbprop"));
        TbPhysics = new TbPhysics(loader("tbphysics"));
        TbLevelBall = new TbLevelBall(loader("tblevelball"));
        TbLevelPocket = new TbLevelPocket(loader("tblevelpocket"));
        TbLevelProp = new TbLevelProp(loader("tblevelprop"));
        TbLevelGeometry = new TbLevelGeometry(loader("tblevelgeometry"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbLevel.ResolveRef(this);
        TbBoard.ResolveRef(this);
        TbBall.ResolveRef(this);
        TbProp.ResolveRef(this);
        TbPhysics.ResolveRef(this);
        TbLevelBall.ResolveRef(this);
        TbLevelPocket.ResolveRef(this);
        TbLevelProp.ResolveRef(this);
        TbLevelGeometry.ResolveRef(this);
    }
}

}
