
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// Ball
/// </summary>
public partial class TbBall
{
    private readonly System.Collections.Generic.Dictionary<int, Ball> _dataMap;
    private readonly System.Collections.Generic.List<Ball> _dataList;
    
    public TbBall(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Ball>(n);
        _dataList = new System.Collections.Generic.List<Ball>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Ball _v;
            _v = global::GameConfig.Ball.DeserializeBall(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Ball> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Ball> DataList => _dataList;

    public Ball GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Ball Get(int key) => _dataMap[key];
    public Ball this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

