
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// Board
/// </summary>
public partial class TbBoard
{
    private readonly System.Collections.Generic.Dictionary<int, Board> _dataMap;
    private readonly System.Collections.Generic.List<Board> _dataList;
    
    public TbBoard(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Board>(n);
        _dataList = new System.Collections.Generic.List<Board>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Board _v;
            _v = global::GameConfig.Board.DeserializeBoard(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Board> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Board> DataList => _dataList;

    public Board GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Board Get(int key) => _dataMap[key];
    public Board this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

