
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// LevelGeometry
/// </summary>
public partial class TbLevelGeometry
{
    private readonly System.Collections.Generic.Dictionary<int, LevelGeometry> _dataMap;
    private readonly System.Collections.Generic.List<LevelGeometry> _dataList;
    
    public TbLevelGeometry(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelGeometry>(n);
        _dataList = new System.Collections.Generic.List<LevelGeometry>(n);
        for(int i = n ; i > 0 ; --i)
        {
            LevelGeometry _v;
            _v = global::GameConfig.LevelGeometry.DeserializeLevelGeometry(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, LevelGeometry> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<LevelGeometry> DataList => _dataList;

    public LevelGeometry GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LevelGeometry Get(int key) => _dataMap[key];
    public LevelGeometry this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

