
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// LevelBall
/// </summary>
public partial class TbLevelBall
{
    private readonly System.Collections.Generic.Dictionary<int, LevelBall> _dataMap;
    private readonly System.Collections.Generic.List<LevelBall> _dataList;
    
    public TbLevelBall(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelBall>(n);
        _dataList = new System.Collections.Generic.List<LevelBall>(n);
        for(int i = n ; i > 0 ; --i)
        {
            LevelBall _v;
            _v = global::GameConfig.LevelBall.DeserializeLevelBall(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, LevelBall> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<LevelBall> DataList => _dataList;

    public LevelBall GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LevelBall Get(int key) => _dataMap[key];
    public LevelBall this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

