
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// LevelTerrain
/// </summary>
public partial class TbLevelTerrain
{
    private readonly System.Collections.Generic.Dictionary<int, LevelTerrain> _dataMap;
    private readonly System.Collections.Generic.List<LevelTerrain> _dataList;
    
    public TbLevelTerrain(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelTerrain>(n);
        _dataList = new System.Collections.Generic.List<LevelTerrain>(n);
        for(int i = n ; i > 0 ; --i)
        {
            LevelTerrain _v;
            _v = global::GameConfig.LevelTerrain.DeserializeLevelTerrain(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, LevelTerrain> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<LevelTerrain> DataList => _dataList;

    public LevelTerrain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LevelTerrain Get(int key) => _dataMap[key];
    public LevelTerrain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

