
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// LevelProp
/// </summary>
public partial class TbLevelProp
{
    private readonly System.Collections.Generic.Dictionary<int, LevelProp> _dataMap;
    private readonly System.Collections.Generic.List<LevelProp> _dataList;
    
    public TbLevelProp(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelProp>(n);
        _dataList = new System.Collections.Generic.List<LevelProp>(n);
        for(int i = n ; i > 0 ; --i)
        {
            LevelProp _v;
            _v = global::GameConfig.LevelProp.DeserializeLevelProp(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, LevelProp> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<LevelProp> DataList => _dataList;

    public LevelProp GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LevelProp Get(int key) => _dataMap[key];
    public LevelProp this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

