
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// Physics
/// </summary>
public partial class TbPhysics
{
    private readonly System.Collections.Generic.Dictionary<int, Physics> _dataMap;
    private readonly System.Collections.Generic.List<Physics> _dataList;
    
    public TbPhysics(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Physics>(n);
        _dataList = new System.Collections.Generic.List<Physics>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Physics _v;
            _v = global::GameConfig.Physics.DeserializePhysics(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Physics> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Physics> DataList => _dataList;

    public Physics GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Physics Get(int key) => _dataMap[key];
    public Physics this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

