
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// Prop
/// </summary>
public partial class TbProp
{
    private readonly System.Collections.Generic.Dictionary<int, Prop> _dataMap;
    private readonly System.Collections.Generic.List<Prop> _dataList;
    
    public TbProp(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Prop>(n);
        _dataList = new System.Collections.Generic.List<Prop>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Prop _v;
            _v = global::GameConfig.Prop.DeserializeProp(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Prop> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Prop> DataList => _dataList;

    public Prop GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Prop Get(int key) => _dataMap[key];
    public Prop this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

