
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// Terrain
/// </summary>
public partial class TbTerrain
{
    private readonly System.Collections.Generic.Dictionary<int, Terrain> _dataMap;
    private readonly System.Collections.Generic.List<Terrain> _dataList;
    
    public TbTerrain(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Terrain>(n);
        _dataList = new System.Collections.Generic.List<Terrain>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Terrain _v;
            _v = global::GameConfig.Terrain.DeserializeTerrain(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Terrain> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Terrain> DataList => _dataList;

    public Terrain GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Terrain Get(int key) => _dataMap[key];
    public Terrain this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

