
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class TerrainStyle : Luban.BeanBase
{
    public TerrainStyle(ByteBuf _buf) 
    {
        TerrainKind = (TerrainKind)_buf.ReadInt();
        PrefabLocation = _buf.ReadString();
        DefaultDuration = _buf.ReadFloat();
        DefaultSpeedMultiplier = _buf.ReadFloat();
        InheritVelocity = _buf.ReadBool();
        InheritRotation = _buf.ReadBool();
    }

    public static TerrainStyle DeserializeTerrainStyle(ByteBuf _buf)
    {
        return new TerrainStyle(_buf);
    }

    public readonly TerrainKind TerrainKind;
    public readonly string PrefabLocation;
    public readonly float DefaultDuration;
    public readonly float DefaultSpeedMultiplier;
    public readonly bool InheritVelocity;
    public readonly bool InheritRotation;
   
    public const int __ID__ = -487577700;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "terrainKind:" + TerrainKind + ","
        + "prefabLocation:" + PrefabLocation + ","
        + "defaultDuration:" + DefaultDuration + ","
        + "defaultSpeedMultiplier:" + DefaultSpeedMultiplier + ","
        + "inheritVelocity:" + InheritVelocity + ","
        + "inheritRotation:" + InheritRotation + ","
        + "}";
    }
}
}

