
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum TerrainKind
    {
        JumpPad = 0,
        Tunnel = 1,
        Pit = 2,
        ReverseBelt = 3,
        Teleporter = 4,
    }

} 

