
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Terrain : Luban.BeanBase
{
    public Terrain(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        TerrainKind = (TerrainKind)_buf.ReadInt();
        PrefabLocation = _buf.ReadString();
        DefaultDuration = _buf.ReadFloat();
        DefaultSpeedMultiplier = _buf.ReadFloat();
        InheritVelocity = _buf.ReadBool();
        InheritRotation = _buf.ReadBool();
    }

    public static Terrain DeserializeTerrain(ByteBuf _buf)
    {
        return new Terrain(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// terrainKind
    /// </summary>
    public readonly TerrainKind TerrainKind;
    /// <summary>
    /// prefabLocation
    /// </summary>
    public readonly string PrefabLocation;
    /// <summary>
    /// defaultDuration
    /// </summary>
    public readonly float DefaultDuration;
    /// <summary>
    /// defaultSpeedMultiplier
    /// </summary>
    public readonly float DefaultSpeedMultiplier;
    /// <summary>
    /// inheritVelocity
    /// </summary>
    public readonly bool InheritVelocity;
    /// <summary>
    /// inheritRotation
    /// </summary>
    public readonly bool InheritRotation;
   
    public const int __ID__ = 241216277;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "terrainKind:" + TerrainKind + ","
        + "prefabLocation:" + PrefabLocation + ","
        + "defaultDuration:" + DefaultDuration + ","
        + "defaultSpeedMultiplier:" + DefaultSpeedMultiplier + ","
        + "inheritVelocity:" + InheritVelocity + ","
        + "inheritRotation:" + InheritRotation + ","
        + "}";
    }
}
}

