
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Triangle : Shape
{
    public Triangle(ByteBuf _buf)  : base(_buf) 
    {
        A = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        B = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
        C = ExternalTypeUtil.NewVector2(global::GameConfig.vector2.Deserializevector2(_buf));
    }

    public static Triangle DeserializeTriangle(ByteBuf _buf)
    {
        return new Triangle(_buf);
    }

    public readonly UnityEngine.Vector2 A;
    public readonly UnityEngine.Vector2 B;
    public readonly UnityEngine.Vector2 C;
   
    public const int __ID__ = 1562406440;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "a:" + A + ","
        + "b:" + B + ","
        + "c:" + C + ","
        + "}";
    }
}
}

