
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class TriggerProp : EffectBinding
{
    public TriggerProp(ByteBuf _buf)  : base(_buf) 
    {
        PropPlacementId = _buf.ReadInt();
        PropPlacementId_Ref = null;
    }

    public static TriggerProp DeserializeTriggerProp(ByteBuf _buf)
    {
        return new TriggerProp(_buf);
    }

    public readonly int PropPlacementId;
    public LevelProp PropPlacementId_Ref;
   
    public const int __ID__ = 986806555;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        PropPlacementId_Ref = tables.TbLevelProp.GetOrDefault(PropPlacementId);
    }

    public override string ToString()
    {
        return "{ "
        + "propPlacementId:" + PropPlacementId + ","
        + "}";
    }
}
}

