
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class UnlockPocket : EffectBinding
{
    public UnlockPocket(ByteBuf _buf)  : base(_buf) 
    {
        PocketPlacementId = _buf.ReadInt();
        PocketPlacementId_Ref = null;
    }

    public static UnlockPocket DeserializeUnlockPocket(ByteBuf _buf)
    {
        return new UnlockPocket(_buf);
    }

    public readonly int PocketPlacementId;
    public LevelPocket PocketPlacementId_Ref;
   
    public const int __ID__ = -1207553510;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
        PocketPlacementId_Ref = tables.TbLevelPocket.GetOrDefault(PocketPlacementId);
    }

    public override string ToString()
    {
        return "{ "
        + "pocketPlacementId:" + PocketPlacementId + ","
        + "}";
    }
}
}

